SELECT
    M.FRT_APP_NO,
    M.CGO_MODE_CD,
    M.POL_CTR_CD,
    M.POL_PORT_CD,
    M.POL_TRML_CD,
    M.POD_CTR_CD,
    M.POD_PORT_CD,
    M.POD_TRML_CD
FROM ODS_ICC.SA201M M
WHERE M.STR_DT <= TO_CHAR(SYSDATE, 'YYYYMMDD')
  AND NVL(M.END_DT, '99991231') >= TO_CHAR(ADD_MONTHS(SYSDATE, -6), 'YYYYMMDD');
