SELECT
    T.SCHG_TRF_NO,
    T.SEQ AS SCHG_TRF_SEQ,
    T.FRT_CD,
    CASE
        WHEN T.FRT_PNC_CD IN ('P', 'C') THEN T.FRT_PNC_CD
        WHEN H.PAY_PLC_CAT_CD = '02' THEN 'P'
        WHEN H.PAY_PLC_CAT_CD = '03' THEN 'C'
        ELSE NULL
    END AS FRT_PNC_CD,
    T.STR_DT,
    T.END_DT,
    T.CGO_MODE_CD,
    T.POL_PLC_TYP_CD,
    T.POL_PLC_NM,
    T.POD_PLC_TYP_CD,
    T.POD_PLC_NM,
    T.CUR_CD,
    T.CNTR_SZ_CD,
    T.CNTR_TYP_CD,
    T.CGO_TYP_CD,
    T.RATE,
    T.EDW_LOAD_DTM
FROM DW_SALES.SP301I02 T
LEFT JOIN ODS_ICC.SA215I H
    ON H.SCHG_TRF_NO = T.SCHG_TRF_NO
WHERE T.BASC_DT = (SELECT MAX(BASC_DT) FROM DW_SALES.SP301I02)
  AND T.FRT_CD = 'EFC'
  AND T.STR_DT <= TO_CHAR(SYSDATE, 'YYYYMMDD')
  AND T.END_DT >= TO_CHAR(SYSDATE, 'YYYYMMDD')
  AND T.UPDT_YN = 'N'
  AND T.EXC_PROC_YN = 'N';
